### ISSUE TITLE
Change predictions sorting

### ISSUE THREAD

**Issue by lopezjuanma96** [OTTAA-Project/Keyboard#16]
For testing the sorting methods, we'll keep the sorting on the cloud function that provides the prediction results, which is easier to deploy. So, until we find the best sorting method, the keyboard app should only get the predictions JSON array and only get the text from each one and put it in the selector widget.

- [x] POST request for prediciton is exactly the same.
- [x] The returned object now has up to 4 keys: "name", "value", "scores", "tokens". For now we **ONLY** need to get the prediction string from the key "name" and in the same order they come from the cloud function response put them on the front-end widget.
- [x] Although we are not using it for now, the "value" key changed from having an array to a single number (double or float), so the reading process should be changed (but then again, this value **WON'T** be used for now in the front-end processing)

**Comment by asimjawad** [comment]
@lopezjuanma96 the value is still coming with an array.

**Comment by lopezjuanma96** [comment]
@asimjawad yes but it's because i was waiting for the changes on the app to change the cloud function, so we could still use it, just changed it to number!
