### ISSUE TITLE
Logo and App name

### ISSUE THREAD

**Issue by hectoritr** [OTTAA-Project/Keyboard#19]
- [x] Change Logo
- [x] Change Name
- [x] Change Package name

**Comment by asimjawad** [comment]
add the required names and icons for this app @hectoritr

**Comment by asimjawad** [comment]
@hectoritr resources for this?

**Comment by hectoritr** [comment]
We are going to go with this icon for now, until the new one is ready. 

App Name: Keyboard by OTTAA
package name: com.stonefacesoft.keyboard

[Keyboard icon.zip](https://github.com/OTTAA-Project/Keyboard/files/9491958/Keyboard.icon.zip)
