### ISSUE TITLE
Increase size of action buttons in the sentence block

### ISSUE THREAD

**Issue by lopezjuanma96** [OTTAA-Project/Keyboard#50]
Since keyboard is mostly going to be used with accessibility devices, we need to increase the size of the erase, backspace, etc that are located in the lower right part of the sentence block, to need less precision on the pointer movements to act on them

**Comment by hectoritr** [comment]
After testing it with accessibility devices, like Bocho and the Eyetracker, we decided that the buttons need to be bigger. So we decided that would be best to add a Setting, Accessibility, Large buttons, and a toggle switch to make the even bigger (Similar size to a letter key)

<img width="582" alt="Screen Shot 2022-09-21 at 14 46 48" src="https://user-images.githubusercontent.com/12820318/191574977-543a4be3-a647-4d7d-932b-4ff15d2acf28.png">


Action plan

- [ ] Add Accesibility in Settings
- [ ] Add Toggle switch "Big buttons"
