### ISSUE TITLE
Prediction on empty phrase

### ISSUE THREAD

**Issue by lopezjuanma96** [OTTAA-Project/Keyboard#9]
Asking for a prediction on an empty phrase should not be allowed, the API won't give an answer and it will only waste requests and processing time. Also, right now it's also raising an error (press space on an empty phrase and see console)

**Comment by hectoritr** [comment]
As said @lopezjuanma96 there's still sending the request on an empty string and also generating an error when handling the null response. 

Response
{"error":"Value for argument \"documentPath\" is not a valid resource path. Path must be a non-empty string."}
Error
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'Map<String, dynamic>'

**Comment by hectoritr** [comment]
Also, as mentioned on #25 Clear predictions, there's a minor bug with adding the space when adding a new prediction from the prediction box. 

The sequence is as follows. 
When writing a sentence and choosing from the prediction boxes, everything goes as planned. 

![Screenshot_1662039093](https://user-images.githubusercontent.com/12820318/187928035-92c54093-cce9-4d4f-a8e5-a3a0c944c151.png)

If I erase the predicted word, when I reach the last word the app predicts again. Which is correct. 
![Screenshot_1662039102](https://user-images.githubusercontent.com/12820318/187928216-c5697719-85d8-4e67-a675-a3077669e831.png)

But, when I choose a new prediction, there is no space between words. Making the TTS fail when speaking and the user has to erase the new prediction to add a space. So we need to add that space. 
![Screenshot_1662039106](https://user-images.githubusercontent.com/12820318/187928441-e24b3f97-404a-4d23-a874-b73fc6e8798e.png)
